### ISSUE TITLE
Error displaying widget

### ISSUE THREAD

**Issue by mjlbach** [maartenbreddels/ipyvolume#295]
To setup ipyvolume, I ran the following commands on a fresh python 3.7 virtualenv on ubuntu 16.04:

```
pip install -U jupyterlab jupytext ipyvolume
jupyter serverextension enable jupytext
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install ipyvolume
jupyter labextension install jupyter-threejs
jupyter lab build
```

After attempting to use ipyvolume scatter  in jupyter lab, I received the following error:
```
Error displaying widget
Error displaying widget: model not found
```

After jupyter lab build again:
```
Error displaying widget
Loading widget...
```

Anyone else having issues? I just noticed this after having used ipyvolume consistently before, so assuming an updated to jupyterlab broke something.

**Comment by thomasaarholt** [comment]
I am getting the same issue. At a guess I would say it is related to the Jupyter Lab 2.0. 
Interestingly, upon installation of ipyvolume, plotting with ipympl no longer works, and reports a similar issue.

I installed by `conda install ipyvolume` which led to these new packages:
```
The following NEW packages will be INSTALLED:
  ipyvolume          conda-forge/noarch::ipyvolume-0.4.6-py_1
  ipywebrtc          conda-forge/win-64::ipywebrtc-0.5.0-py38_0
  traittypes         conda-forge/noarch::traittypes-0.2.1-py_1
```

I have tried several combinations of `jupyter lab build` and `jupyter labextension update --all` without luck. If @maartenbreddels has time, it would be great to get input on what might be going on. I'm currently testing what happens if I create a new env with separately just ipympl, just ipyvolume and another with both together to see if there is a reproducible issue.

**Comment by thomasaarholt** [comment]
I just tried a new environment with 
`conda create --name volume ipyvolume jupyterlab nodejs`
Then called the three jupyter labextension installers. 
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install ipyvolume
jupyter labextension install jupyter-threejs
```
The following code 
```python
import numpy as np
import ipyvolume as ipv
V = np.random.random((128,128,128)) # our 3d array
ipv.quickvolshow(V)
```
results in `Error displaying widget`

**Comment by Karamaz0V1** [comment]
I am getting the same errors with the 0.6.0-alpha. As pointed out by @thomasaarholt I noticed that plotting with ipympl no longer works. 

without ipyvolume, ipympl is working:

    JupyterLab v2.0.1
    Known labextensions:
       app dir: /opt/conda/share/jupyter/lab
            @bokeh/jupyter_bokeh v2.0.0  enabled  OK
            @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
            jupyter-matplotlib v0.7.2  enabled  OK
            jupyter-threejs v2.2.0  enabled  OK
            jupyterlab-datawidgets v6.2.0  enabled  OK

with ipyvolume, ipyvolume and ipympl doesn't work:

    JupyterLab v2.0.1
    Known labextensions:
       app dir: /opt/conda/share/jupyter/lab
            @bokeh/jupyter_bokeh v2.0.0  enabled  OK
            @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
            ipyvolume v0.6.0-alpha.2  enabled  OK
            jupyter-matplotlib v0.7.2  enabled  OK
            jupyter-threejs v2.2.0  enabled  OK
            jupyterlab-datawidgets v6.2.0  enabled  OK

**Comment by danieljdenman** [comment]
i am having the issue with jupyter lab. works with jupyter notebook. i have tried with both:
```
JupyterLab v1.1.4
Known labextensions:
   app dir: /Users/danieljdenman/opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        ipyvolume v0.5.2  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyterlab-datawidgets v6.3.0  enabled  OK
```

and:
```
JupyterLab v1.1.4
Known labextensions:
   app dir: /Users/danieljdenman/opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        ipyvolume v0.6.0-alpha.1  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK```

has anyone been able to get this to work recently?

**Comment by fschiffers** [comment]
I am on Jupyter Lab 2.0.1 and also get the "Error displaying widget".

**Comment by sitzikbs** [comment]
Same issue for me.  Using Python 3.7 and Jupyter lab 2.0.1.  
I closed my #307 as it is a duplicate, all of my specs are there (should probably also mention that I am using ubuntu 18.04).

**Comment by uros-tm** [comment]
Same issue + workaround - Jupyter lab 2.1.0 (mac) and 1.2.7 (GCP AI Notebooks instance).

**Comment by maartenbreddels** [comment]
The 
This should be fixed due to https://github.com/conda-forge/ipyvolume-feedstock/pull/32 we now build noarch and #319 
`pip install ipyvolume==0.6.0a3` and I might also release the conda-forge package (alpha release)

**Comment by maartenbreddels** [comment]
Correction: `pip install ipyvolume==0.6.0a3` and https://github.com/conda-forge/ipyvolume-feedstock/pull/34

**Comment by pratulyab** [comment]
I was able to resolve this for `jupyterlab` `2.1.4` by installing:
- latest ipyvolume release
  - `pip install ipyvolume==0.6.0a6` (pre-release)

- bqplot
  - `pip install bqplot`
  - `jupyter labextension install bqplot`

#### Packages' versions:

- Python packages:
    - jupyterlab==2.1.4
    - jupyterlab-server==1.2.0
    - ipywidgets==7.5.1
    - bqplot==0.12.17
- labextensions (enabled npm packages)
  -  @jupyter-widgets/jupyterlab-manager v2.0.0
  - bqplot v0.5.17
  - ipyvolume v0.6.0-alpha.5
  - jupyter-threejs v2.2.0
  - jupyterlab-datawidgets v6.2.0

**Comment by HaoranZhuExplorer** [comment]
I'm using the latest version of ipyvolume. Followed all the steps above, I still have the same issue, can you help me with that@maartenbreddels ?

**Comment by HaoranZhuExplorer** [comment]
I finally solved the problem by using jupyter notebook. For jupyter lab, I don't know why it doesn't work...

**Comment by codenie** [comment]
I use jupyterlab3 and meet the same problem. However, the same code works in jupyter notebook. 
Thus, one possible solution: launch classic jupyter notebook and run your code again.

**Comment by danielyan86129** [comment]
Same issue here: only works in jupyter notebook (after applying @pratulyab 's suggested installs), but jupyter lab never works...

- ipyvolume 0.6.0a6
- Chrome Version 101.0.4951.64 (Official Build) (x86_64)
- jupyter-server 1.17.0
- jupyterlab 3.4.2
- jupyter 1.0.0

**Comment by doshin2021** [comment]
Hi all,
Same issue with jupyter lab. However, I couldn't make it work on classic jupyt either.
Can someone please post the config for the classic one?
Thanks
